module2-task1: add index.html
htmlacademy-adaptive/1279673-pink-23 pull request #2
Opened 2021-07-26 15:13 UTC by vorobushka

2021-07-27 07:59 UTC, lipa88-mk requested changes
В целом очень даже хорошее начало, с БЭМ всего пара моментов есть)  Обязательно нужно проверить разметку валидатором, тк есть ошибки, нужно немного поработать с семантикой, везде картинкам задать альты, а ссылкам правильный href :)

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +  <body class="page__body">
page__body - это элемент блока page, которого нет. Надо добавить

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
>      <meta charset="utf-8">
Обязательно проверяем верстку валидатором https://validator.w3.org/nu, тк есть ошибки: у картинок нет альтов, есть незакрытые теги. Это не позволит пройти проверкам эдиторконфига и смержить ПР.

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +      <a class="page-header__logo" href="">
href не оставляем пустыми - либо пишет туда файл/ссылку, либо ставим заглушку # . Плюс у некоторых ссылок по ТЗ указано, куда они должны вести. Так что все ссылки нужно проверить и указать верное. Так же href можно удалить, например, для лого на главной, тк мы уже на ней и ссылаться сами на себя нет смысла)

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +            <a href="" class="download__icon"><img class="page-header__logo-image" src="img/microsoft-logo.svg" alt="" width="41" height="44"></a>
Элемент не может быть вне блока page-header. Это элемент блока download

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +      <h1 class="visually-hidden">Заголовок</h1>
Текст должен быть подходящим для этой страницы

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +          <h1 class="advantages__slogan">Нам есть, что вам предложить!</h1>
Заголовок 1 уже был, он используется только 1 раз. Данный текст - это не заголовок, просто параграф с оформлением, тк текст по смыслу не несет полезной нагрузки.

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +            <table class="price__table slider__item">
Тут лучше ориентироваться на таблицу в планшетной или десктопной версии, тк на мобильном она видна не вся.  В полях с иконками появляется текст, первый столбец скрывается, видны 3 столбца База, Стандарт, Анлим.

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +          <dl class="contacts__list">
список определений тут не очень подходит. Лучше просто параграфы

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +            <img class="page-footer__logo-pink" src="img/pink-grey.svg" width="74" height="23" alt="" >
Это одна иконка, делить на части не нужно, на десктопе потом будет другая. И лого всегда ссылка на главную)

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +              <img src="img/twitter.svg" width="18" height="14" alt="">
Тут круг не нужен, он будет делаться стилями. И это не просто картинка - это ссылка на соцсеть.

2021-07-27 07:59 UTC, lipa88-mk commented on source/index.html
> +            <img src="img/htmlacademy.svg" alt="" width="27" height="34">
Тоже ссылка с адресом по ТЗ

2021-07-29 08:07 UTC, vorobushka commented on source/index.html
> +            <table class="price__table slider__item">
я не поняла, как нужно поменять таблицу

2021-07-29 18:00 UTC, merged