module3-task1: add blocks
htmlacademy-adaptive/1279673-pink-23 pull request #4
Opened 2021-08-17 15:40 UTC by vorobushka

2021-08-18 07:55 UTC, lipa88-mk commented
Сразу перечислю что глобально нужно поправить: 

1. Остались ошибки по тесту - в паре мест не хватает пробелов, надо поправить. 
2. Шрифт макета не подключен, уже пора. Для этого нужен отдельный less файл, например, fonts, не в папке блоков.  Шрифты подключаются локально из папки.
3.  названия файлов в папке blocks не соответствуют классам бэм блоков. Например, в разметке есть блок downloads-photo, а файл называется downloads, что не верно.  А в файле form.less находится отдельный блок form-register. Он доле быть отдельным блоком и файлом. Тоже самое с бэм-блоком page-header, page-footer и может еще где-то. Каждый бэм-блок - отдельный файл. В каждом файле должно быть только то, что относится именно к этому блоку. 
4. Сетки на данном этапе делать не нужно, внимание нужно уделить шрифту, цвету и стилям текстовых блоков, можно добавить margin-bottom после текстовых элементов, добавить фоновые цвета и всё. Если какие-то свойства текстовых элементов, например, заголовков, повторяются на разных страницах, то можно подумать о примесях или отдельном БЭМ-блоке.  

По сути, в этом задании на свойствах оформления текста мы тренируемся работе с препроцессором, чтобы освоиться, начать работу со стилями. Все-все текстовые элементы должна бать по макету, это один из базовых критериев - цвет, жирность, междустрочный интервал. Внешне черный не всегда #000, также и с белым :) Это всё надо проверять по макету

2021-08-18 07:57 UTC, lipa88-mk requested changes
В целом начало очень неплохое, пройдись по списку, что написала в комментарии, осталось на самом деле тут немного доделать и можно будет переходить к более интересной работе с сетками)

2021-08-18 07:57 UTC, lipa88-mk commented on source/catalog.html
> +          Видите, как не хватает ваших?</div>
Если это заголовок, то почему бы не использовать тег заголовка вместо дива?) А ниже - это параграф с описанием, тоже див лучше заменить

2021-08-18 07:57 UTC, lipa88-mk commented on source/less/blocks/page.less
> +.page-header {
отдельный файл

2021-08-18 07:57 UTC, lipa88-mk commented on source/less/blocks/page.less
> +.page-footer__wrapper {
в отдельный файл

2021-08-18 07:57 UTC, lipa88-mk commented on source/less/style.less
> +@import 'blocks/page.less';
не хватает подключения шрифтов

2021-08-20 12:52 UTC, vorobushka commented on source/catalog.html
> +          Видите, как не хватает ваших?</div>
а про какой параграф с описанием вы говорите? ниже идет форма

2021-08-23 12:35 UTC, lipa88-mk commented on source/catalog.html
> +          Видите, как не хватает ваших?</div>
Я говорила про текст над формой - это лучше сделать не дивом, а подходящим текстовым тегом)

2021-08-23 12:38 UTC, lipa88-mk commented
Да, отлично! Но стоит еще обращать внимание на раздел checks (https://github.com/htmlacademy-adaptive/1279673-pink-23/pull/4/checks) после создания пулл реквеста - тут видим, что есть ошибки эдиторконфига, которые нужно поправить в дальнейшем

2021-08-23 12:38 UTC, merged